// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocalSetupResult = { run_id: string, workspace_id: string | null, workspace_name: string | null, };