// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolStatus } from "./ToolStatus";

export type MacInspect = { tmux: ToolStatus, tmux_conf_ok: boolean, };