// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PaneAgentSnapshot = { state: string, state_since: number | null, started_at: number | null, avg_ms: number | null, seq: number, };
