// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectFolder = { id: string, 
/**
 * Display label. Defaults to the path's basename at creation time;
 * the user can rename it without moving anything.
 */
name: string, 
/**
 * Absolute path on the workspace's host.
 */
path: string, 
/**
 * Persisted collapsed/open state of the worktree list.
 */
is_collapsed: boolean, };