// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Connection } from "./Connection";

export type ProjectFolder = { id: string, 
/**
 * Display label. Defaults to the path's basename at creation time;
 * the user can rename it without moving anything.
 */
name: string, 
/**
 * Absolute path to the repo root, on `connection`'s host.
 */
path: string, 
/**
 * How to reach the host. `None` = this machine.
 */
connection: Connection | null, 
/**
 * Persisted collapsed/open state of the section.
 */
is_collapsed: boolean, 
/**
 * 0-based sort key across project-folder sections. Same convention
 * as `WorkspaceGroup::sort_order` — absent until something is
 * actually reordered, so the file round-trips byte-identical.
 */
sort_order: number | null, };