// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a workspace's tickets live, and why. Returned to the frontend
 * so the capture modal can show the destination BEFORE saving — writing
 * into someone's repo should never be a surprise.
 */
export type ProjectResolution = { 
/**
 * Absolute project root, when one could be derived.
 */
project_path: string | null, 
/**
 * Directory tickets are actually written to.
 */
tickets_dir: string, 
/**
 * True when `tickets_dir` is inside the project (the good case);
 * false when we fell back to app-local storage.
 */
in_project: boolean, 
/**
 * Which rung of the ladder produced `project_path`, for the UI to
 * explain itself: "override" | "worktree" | "git" | "cwd" | "none".
 */
source: string, 
/**
 * Why we fell back, when `in_project` is false. Empty otherwise.
 */
fallback_reason: string, };