// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RtlProfile } from "./RtlProfile";

/**
 * 2026-08-19: RTL settings, split by what the pane is talking to. Measured
 * live on 2026-08-19, both directions, same app, same build:
 *
 *   - A **remote** pane (SSH to Linux) delivers Hebrew in LOGICAL order, so
 *     `auto_per_line` renders it correctly and `off` renders it reversed.
 *   - A **local** pane (native Windows ConPTY) delivers Hebrew ALREADY IN
 *     VISUAL order — `auto_per_line` right-aligns it correctly but reverses
 *     the letters, because the browser's bidi pass is then the SECOND one.
 *     Windows console keeps RTL text visually ordered in its screen buffer
 *     and ConPTY re-emits that buffer; Linux just passes bytes through.
 *
 * So the two classes need OPPOSITE modes, not different tuning of one mode,
 * and a single global setting could only ever satisfy one of them. Yossi hit
 * this as "ההגדרה הזו עובדת או למקומי או למרוחק".
 *
 * The split axis is `ConnCaps.posixExec` (`app/src/types.ts`), not a
 * local/remote boolean: **WSL counts as remote**, because it is Linux with
 * tmux and a Linux Claude, and is "local" only geographically.
 */
export type RtlProfiles = { 
/**
 * Native Windows panes (ConPTY: cmd, PowerShell). Not WSL.
 */
local: RtlProfile, 
/**
 * Anything with a POSIX shell behind it — SSH and WSL.
 */
remote: RtlProfile, };