// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 2026-08-19: RTL handling for ONE class of pane. The four knobs used to be
 * flat on `TerminalSettings`, i.e. global, which made the two classes
 * mutually exclusive — see `RtlProfiles`.
 */
export type RtlProfile = { 
/**
 * "auto_per_line" (DOM renderer + per-row dir), "bidi_reorder"
 * (WebGL + our logical→visual reorder), or "off" (WebGL, raw).
 */
rtl_mode: string, auto_direction: boolean, mirror_arrows_rtl: boolean, tui_owns_bidi: boolean, };