// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 2026-08-19: RTL handling for ONE class of pane. The four knobs used to be
 * flat on `TerminalSettings`, i.e. global, which made the two classes
 * mutually exclusive — see `RtlProfiles`.
 */
export type RtlProfile = { 
/**
 * "auto_per_line" (DOM renderer + per-row dir), "bidi_reorder"
 * (WebGL + our logical→visual reorder), or "off" (WebGL, raw).
 */
rtl_mode: string, auto_direction: boolean, mirror_arrows_rtl: boolean, tui_owns_bidi: boolean, 
/**
 * Which rule decides a row's paragraph direction: `"any_rtl"` (any Hebrew
 * on the row takes it RTL — what every version before 2026-08-19 did, and
 * what remote panes are known to render correctly) or `"tui_dominance"`
 * (the RTL_DOMINANCE vote in `app/src/textDirection.ts`, which stops a TUI
 * status bar from mirroring its own layout).
 *
 * Keyed on the PANE CLASS on purpose. The vote first shipped keyed on
 * whether Claude Code held the pane, and since the OSC title propagates
 * over SSH it fired on remote panes and broke a working path. Absent from
 * an existing settings.json this reads as `"any_rtl"`, so an upgrade
 * cannot silently move a pane onto the newer rule.
 */
direction_policy: string, };