// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TicketElement = { xpath: string, selector: string, html: string, 
/**
 * Free-form JSON blob of computed style / bounding box. The
 * frontend fills whatever it can capture; the backend just
 * round-trips it.
 */
style: unknown, };