// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TicketElement } from "./TicketElement";

export type Ticket = { id: string, 
/**
 * ISO-8601 (UTC).
 */
created: string, url: string, element: TicketElement, 
/**
 * Filename inside the workspace's tickets dir (relative), not an
 * absolute path. `None` when no screenshot was captured.
 */
screenshot_path: string | null, description: string, 
/**
 * Persisted as one of `"open" | "resolved"`. Kept as a String so
 * future statuses don't need a migration.
 */
status: string, workspace_id: string, 
/**
 * Placeholder for a later auto-fix hand-off (Claude Code hint).
 * Always serialized so the schema is stable.
 */
source_hint: string | null, };