// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry from `git worktree list --porcelain`.
 *
 * Not persisted — this is the shape of a scan result handed to the UI.
 */
export type WorktreeEntry = { 
/**
 * Absolute path on the project folder's host.
 */
path: string, 
/**
 * Short branch name (`refs/heads/` stripped). None when detached.
 */
branch: string | null, 
/**
 * Commit the worktree is checked out at. Empty for a bare main entry.
 */
head: string, 
/**
 * The first entry git reports is the main working tree.
 */
is_main: boolean, is_detached: boolean, is_locked: boolean, 
/**
 * git considers the entry removable (its directory is gone).
 */
is_prunable: boolean, };