// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WslInspect = { wsl_present: boolean, wsl_ready: boolean, distros: Array<string>, default_distro: string | null, tmux_installed: boolean | null, 
/**
 * "ok" | "stale" | "missing" — winmux CLI inside the distro vs the
 * embedded manifest sha.
 */
winmux_cli_state: string | null, tmux_conf_ok: boolean | null, claude_inside: boolean | null, hooks_version_inside: string | null, };