// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the wizard needs to know before it offers to run the WSL chain.
 */
export type WslPreflight = { 
/**
 * `wsl --status` answers — the Windows features are enabled.
 */
platform_ready: boolean, 
/**
 * At least one distro is registered.
 */
distro_present: boolean, 
/**
 * This ymux process holds an elevated token.
 */
elevated: boolean, 
/**
 * Installing the platform needs admin and we don't have it, so a UAC
 * prompt is unavoidable. False once the platform is already up —
 * adding a further distro to a live platform needs no elevation.
 */
needs_elevation: boolean, };